name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

# Custom domain configuration
[[routes]]
pattern = "blazenote-backend.hanyang8811.work"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "5b2bf001-246c-4b4b-84b9-e76f053c5326"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true
